In [1]:
cd D:\\Saarbrucken\\EDA_Research\\vae-disentanglement\\disentanglement_lib_pl

D:\Saarbrucken\EDA_Research\vae-disentanglement\disentanglement_lib_pl


In [2]:
import torch
import numpy as np
import pandas as pd
import seaborn, time
import torch.nn.functional as F

from torch.nn import init
from torch import nn

from common import dag_utils
from common.special_modules import DAGInteractionLayer
from collections import namedtuple
from models import cs_vae

In [5]:
adj_mat = [(), (27,), (4,), (0,), (13,), (1,), (31,), (4,), (7,), (1,), 
           (17,), (27,), (27,), (27,), (24,), (17,), (14,), (13,), (12,), 
           (12,), (11,), (31,), (11,), (17,), (12,), (13,), (31,), (0,), 
           (13,), (13,), (1,), (13,), (27,)]
parents = [3]
children = [1, 11, 12, 13, 32]

dag_layer = DAGInteractionLayer(
    parents_list=parents, 
    children_list=children, 
    adjacency_matrix=adj_mat, 
    interm_unit_dim=2, 
    bias=True,
    parent_is_root=True
)
print(dag_layer)

DAGInteractionLayer(
  (inp_to_interm): InputToIntermediate()
  (interm1): Intermediate()
  (out): IntermediateToOutput()
)


In [8]:
dag_layer(torch.rand(size=(1, 10)) + 2, current_device=torch.device("cpu"))

tensor([[1.0162, 2.7866, 0.0000, 0.9984, 0.0000, 0.8464, 1.2200, 0.0000, 2.7388,
         0.0000]], grad_fn=<ReluBackward0>)
tensor([[2.5050, 0.0000, 0.5853, 0.0000, 0.1648, 0.0000, 0.0385, 0.3169, 0.0302,
         0.5128, 0.6709, 0.5184, 0.0000, 1.3648, 0.0000]],
       grad_fn=<ReluBackward0>)


(tensor([[0.7016, 0.0188, 0.0000, 0.0000, 0.0000]], grad_fn=<ReluBackward0>),
 tensor([[0.0000, 0.0000, 0.1227, 0.0000, 0.0000]], grad_fn=<ReluBackward0>))

In [5]:
torch.randn(size=(1, 2)) + 1

tensor([[ 2.1527, -1.7286]])

In [8]:
from collections import namedtuple

NetworkArgs = namedtuple("NetworkArgs", ["encoder","decoder","interm_unit_dim", 
                                         "z_dim", "num_channels", "image_size", 
                                        "batch_size", "root_dim"])
network_args = NetworkArgs(
    ['SimpleGaussianConv64'],
    ['SimpleConv64'],
    2,
    10,
    3,
    64,
    128,
    10
)
adjacency_matrix = [(), (27,), (4,), (0,), (13,), (1,), (31,), (4,), (7,), (1,), 
           (17,), (27,), (27,), (27,), (24,), (17,), (14,), (13,), (12,), 
           (12,), (11,), (31,), (11,), (17,), (12,), (13,), (31,), (0,), 
           (13,), (13,), (1,), (13,), (27,)]
test_vae = cs_vae.ConceptStructuredVAE(adjacency_matrix, network_args)

#print(test_vae)

TypeError: __init__() takes 2 positional arguments but 3 were given

In [5]:
# len(adjacency_matrix), sum([len(dag_layer) for dag_layer in test_vae.dag_layer_nodes]), test_vae.dag_layer_nodes

In [5]:
# pass an image and see if dims are correct
test_imgs = torch.rand(2,3,64,64)

In [6]:
#bu_net_outs = test_vae._bottom_up_pass(test_imgs)
#td_net_outs = test_vae._top_down_pass(bu_net_outs)
len(test_vae.adjacency_matrix) - 1 + test_vae.root_dim

42

In [7]:
#fwd_pass_results = test_vae(test_imgs)

test_vae.decoder

SimpleConv64(
  (main): Sequential(
    (0): Unsqueeze3D()
    (1): Conv2d(42, 256, kernel_size=(1, 1), stride=(2, 2))
    (2): ReLU(inplace=True)
    (3): ConvTranspose2d(256, 256, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (4): ReLU(inplace=True)
    (5): ConvTranspose2d(256, 128, kernel_size=(4, 4), stride=(2, 2))
    (6): ReLU(inplace=True)
    (7): ConvTranspose2d(128, 128, kernel_size=(4, 4), stride=(2, 2))
    (8): ReLU(inplace=True)
    (9): ConvTranspose2d(128, 64, kernel_size=(4, 4), stride=(2, 2))
    (10): ReLU(inplace=True)
    (11): ConvTranspose2d(64, 64, kernel_size=(4, 4), stride=(2, 2))
    (12): ReLU(inplace=True)
    (13): ConvTranspose2d(64, 3, kernel_size=(3, 3), stride=(1, 1))
  )
)

In [8]:
fwd_pass_results = test_vae(test_imgs)

torch.Size([2, 42])


In [12]:
import pickle

pickle.dump(adjacency_matrix, 
open('D:\\Saarbrucken\\EDA_Research\\thesis_code\\adjacency_matrices\\celeba.pkl','wb')
)

In [10]:
pwd

'D:\\Saarbrucken\\EDA_Research\\thesis_code\\disentanglement_lib_pl'

In [14]:
p = 'D:\\Saarbrucken\\EDA_Research\\thesis_code\\disentanglement_lib_pl'

isinstance(p, str), isinstance(p, list)

(True, False)

In [17]:
pickle.load(
    open('D:\\Saarbrucken\\EDA_Research\\thesis_code\\adjacency_matrices\\celeba.pkl', 
'rb'))

[(),
 (27,),
 (4,),
 (0,),
 (13,),
 (1,),
 (31,),
 (4,),
 (7,),
 (1,),
 (17,),
 (27,),
 (27,),
 (27,),
 (24,),
 (17,),
 (14,),
 (13,),
 (12,),
 (12,),
 (11,),
 (31,),
 (11,),
 (17,),
 (12,),
 (13,),
 (31,),
 (0,),
 (13,),
 (13,),
 (1,),
 (13,),
 (27,)]

In [46]:
class PriorGNNLayer(nn.Module):
    """
    For now in this impl. all prior nodes have 1-D features 
    """
    def __init__(self, num_nodes, adj_mat, is_final_layer=False):
        super().__init__()

        self.num_nodes = num_nodes
        self.is_final_layer = is_final_layer
        self.A = adj_mat.T # this is reqd because the stored mat is in from-to form but the impl needs to-from

        self.num_neighbours = self.A.sum(dim=0, keepdims=True)

        # Represents a diagonal weight matrix W so that all dims can be 
        # multiplied by a unique scalar i.e. z = Wg + b
        # Features are 1-D
        self.projection_W = nn.Parameter(torch.Tensor(1, self.num_nodes))
        self.projection_b = nn.Parameter(torch.Tensor(self.num_nodes))

        self._init_params()
    
    def _init_params(self):
        
        init.kaiming_normal_(self.projection_W)
        self.projection_b.data.fill_(0)
    
    def forward(self, node_feats):
        
        self.A = self.A.to(node_feats.device)
        self.num_neighbours = self.num_neighbours.to(node_feats.device)
        self.projection_W = self.projection_W.to(node_feats.device)
        self.projection_b = self.projection_b.to(node_feats.device)

        node_feats = self.projection_W.mul(node_feats) + self.projection_b
        print(node_feats)
        node_feats = torch.matmul(node_feats, self.A)
        print(node_feats)
        print(self.num_neighbours)
        node_feats = node_feats / self.num_neighbours

        return node_feats if self.is_final_layer else torch.tanh(node_feats)


In [56]:
A = torch.Tensor(
        [[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 0., 1.]])

prior_layer = PriorGNNLayer(4, A, True)

In [48]:
node_feats = torch.from_numpy( np.random.choice(a=4, size=(2, 4))).type(torch.FloatTensor)
print(node_feats)

tensor([[3., 0., 0., 3.],
        [3., 2., 1., 2.]])


In [49]:
prior_layer.projection_W, prior_layer.projection_b

(Parameter containing:
 tensor([[-0.8105, -0.6637,  0.1299, -0.6581]], requires_grad=True),
 Parameter containing:
 tensor([0., 0., 0., 0.], requires_grad=True))

In [57]:
prior_layer(node_feats)

tensor([[ 1.6835,  0.0000,  0.0000, -2.1513],
        [ 1.6835, -2.2840,  0.1927, -1.4342]], grad_fn=<AddBackward0>)
tensor([[ 1.6835,  0.0000,  1.6835, -0.4678],
        [ 1.6835, -2.2840, -0.4078, -2.0346]], grad_fn=<MmBackward>)
tensor([[1., 1., 3., 3.]])


tensor([[ 1.6835,  0.0000,  0.5612, -0.1559],
        [ 1.6835, -2.2840, -0.1359, -0.6782]], grad_fn=<DivBackward0>)

In [55]:
-2.4315 -1.3274 - 1.3162

-5.0751

In [61]:
prior_layer.num_neighbours[0][2]

tensor(3.)

In [24]:
An = np.array(
        [[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 0., 1.]])

In [28]:
nn=An.sum(axis=-1, keepdims=True)

In [32]:
nn

array([[1.],
       [1.],
       [3.],
       [3.]])

In [31]:
int(nn[0])

1

In [69]:
L = np.random.choice(10,(2,5))

In [86]:
np.nonzero(An == 1)

(array([0, 1, 2, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 0, 1, 2, 0, 1, 3], dtype=int64))

In [84]:
#pa = An[2].nonzero()[0]

L[np.nonzero(An == 1)]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [75]:
L

array([[8, 4, 0, 4, 2],
       [6, 5, 1, 5, 7]])

In [78]:
L[: ,[0, 1, 2]].shape

(2, 3)

In [3]:
L=torch.from_numpy(np.random.choice(10,(2,5)))

In [4]:
L

tensor([[2, 2, 9, 2, 1],
        [7, 4, 8, 4, 8]], dtype=torch.int32)

In [5]:
L[:,[0,2,3]]

tensor([[2, 9, 2],
        [7, 8, 4]], dtype=torch.int32)

In [12]:
a,b=torch.rand(size=(10,1)),torch.rand(size=(10,1))

In [33]:
c=torch.cat([a,b],dim=1).reshape(10,2,1)

In [34]:
c.shape

torch.Size([10, 2, 1])

In [36]:
(*(1,2),3)

(1, 2, 3)