In [1]:
cd D:\\Saarbrucken\\EDA_Research\\vae-disentanglement\\disentanglement_lib_pl

D:\Saarbrucken\EDA_Research\vae-disentanglement\disentanglement_lib_pl


In [2]:
import torch
import numpy as np
import pandas as pd
import seaborn, time
import torch.nn.functional as F

from common import dag_utils
from common.special_modules import DAGInteractionLayer
from collections import namedtuple
from models import cs_vae

In [5]:
adj_mat = [(), (27,), (4,), (0,), (13,), (1,), (31,), (4,), (7,), (1,), 
           (17,), (27,), (27,), (27,), (24,), (17,), (14,), (13,), (12,), 
           (12,), (11,), (31,), (11,), (17,), (12,), (13,), (31,), (0,), 
           (13,), (13,), (1,), (13,), (27,)]
parents = [3]
children = [1, 11, 12, 13, 32]

dag_layer = DAGInteractionLayer(
    parents_list=parents, 
    children_list=children, 
    adjacency_matrix=adj_mat, 
    interm_unit_dim=2, 
    bias=True,
    parent_is_root=True
)
print(dag_layer)

DAGInteractionLayer(
  (inp_to_interm): InputToIntermediate()
  (interm1): Intermediate()
  (out): IntermediateToOutput()
)


In [8]:
dag_layer(torch.rand(size=(1, 10)) + 2, current_device=torch.device("cpu"))

tensor([[1.0162, 2.7866, 0.0000, 0.9984, 0.0000, 0.8464, 1.2200, 0.0000, 2.7388,
         0.0000]], grad_fn=<ReluBackward0>)
tensor([[2.5050, 0.0000, 0.5853, 0.0000, 0.1648, 0.0000, 0.0385, 0.3169, 0.0302,
         0.5128, 0.6709, 0.5184, 0.0000, 1.3648, 0.0000]],
       grad_fn=<ReluBackward0>)


(tensor([[0.7016, 0.0188, 0.0000, 0.0000, 0.0000]], grad_fn=<ReluBackward0>),
 tensor([[0.0000, 0.0000, 0.1227, 0.0000, 0.0000]], grad_fn=<ReluBackward0>))

In [5]:
torch.randn(size=(1, 2)) + 1

tensor([[ 2.1527, -1.7286]])

In [8]:
from collections import namedtuple

NetworkArgs = namedtuple("NetworkArgs", ["encoder","decoder","interm_unit_dim", 
                                         "z_dim", "num_channels", "image_size", 
                                        "batch_size", "root_dim"])
network_args = NetworkArgs(
    ['SimpleGaussianConv64'],
    ['SimpleConv64'],
    2,
    10,
    3,
    64,
    128,
    10
)
adjacency_matrix = [(), (27,), (4,), (0,), (13,), (1,), (31,), (4,), (7,), (1,), 
           (17,), (27,), (27,), (27,), (24,), (17,), (14,), (13,), (12,), 
           (12,), (11,), (31,), (11,), (17,), (12,), (13,), (31,), (0,), 
           (13,), (13,), (1,), (13,), (27,)]
test_vae = cs_vae.ConceptStructuredVAE(adjacency_matrix, network_args)

#print(test_vae)

TypeError: __init__() takes 2 positional arguments but 3 were given

In [5]:
# len(adjacency_matrix), sum([len(dag_layer) for dag_layer in test_vae.dag_layer_nodes]), test_vae.dag_layer_nodes

In [5]:
# pass an image and see if dims are correct
test_imgs = torch.rand(2,3,64,64)

In [6]:
#bu_net_outs = test_vae._bottom_up_pass(test_imgs)
#td_net_outs = test_vae._top_down_pass(bu_net_outs)
len(test_vae.adjacency_matrix) - 1 + test_vae.root_dim

42

In [7]:
#fwd_pass_results = test_vae(test_imgs)

test_vae.decoder

SimpleConv64(
  (main): Sequential(
    (0): Unsqueeze3D()
    (1): Conv2d(42, 256, kernel_size=(1, 1), stride=(2, 2))
    (2): ReLU(inplace=True)
    (3): ConvTranspose2d(256, 256, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (4): ReLU(inplace=True)
    (5): ConvTranspose2d(256, 128, kernel_size=(4, 4), stride=(2, 2))
    (6): ReLU(inplace=True)
    (7): ConvTranspose2d(128, 128, kernel_size=(4, 4), stride=(2, 2))
    (8): ReLU(inplace=True)
    (9): ConvTranspose2d(128, 64, kernel_size=(4, 4), stride=(2, 2))
    (10): ReLU(inplace=True)
    (11): ConvTranspose2d(64, 64, kernel_size=(4, 4), stride=(2, 2))
    (12): ReLU(inplace=True)
    (13): ConvTranspose2d(64, 3, kernel_size=(3, 3), stride=(1, 1))
  )
)

In [8]:
fwd_pass_results = test_vae(test_imgs)

torch.Size([2, 42])


In [12]:
import pickle

pickle.dump(adjacency_matrix, 
open('D:\\Saarbrucken\\EDA_Research\\thesis_code\\adjacency_matrices\\celeba.pkl','wb')
)

In [10]:
pwd

'D:\\Saarbrucken\\EDA_Research\\thesis_code\\disentanglement_lib_pl'

In [14]:
p = 'D:\\Saarbrucken\\EDA_Research\\thesis_code\\disentanglement_lib_pl'

isinstance(p, str), isinstance(p, list)

(True, False)

In [17]:
pickle.load(
    open('D:\\Saarbrucken\\EDA_Research\\thesis_code\\adjacency_matrices\\celeba.pkl', 
'rb'))

[(),
 (27,),
 (4,),
 (0,),
 (13,),
 (1,),
 (31,),
 (4,),
 (7,),
 (1,),
 (17,),
 (27,),
 (27,),
 (27,),
 (24,),
 (17,),
 (14,),
 (13,),
 (12,),
 (12,),
 (11,),
 (31,),
 (11,),
 (17,),
 (12,),
 (13,),
 (31,),
 (0,),
 (13,),
 (13,),
 (1,),
 (13,),
 (27,)]